SDL_Surface* q = SDL_LoadBMP("letters/q.bmp");
SDL_Surface* w = SDL_LoadBMP("letters/w.bmp");
SDL_Surface* e = SDL_LoadBMP("letters/e.bmp");
SDL_Surface* r = SDL_LoadBMP("letters/r.bmp");
SDL_Surface* t = SDL_LoadBMP("letters/t.bmp");
SDL_Surface* yi = SDL_LoadBMP("letters/y.bmp");
SDL_Surface* u = SDL_LoadBMP("letters/u.bmp");
SDL_Surface* i = SDL_LoadBMP("letters/i.bmp");
SDL_Surface* o = SDL_LoadBMP("letters/o.bmp");
SDL_Surface* p = SDL_LoadBMP("letters/p.bmp");
SDL_Surface* a = SDL_LoadBMP("letters/a.bmp");
SDL_Surface* s = SDL_LoadBMP("letters/s.bmp");
SDL_Surface* d = SDL_LoadBMP("letters/d.bmp");
SDL_Surface* f = SDL_LoadBMP("letters/f.bmp");
SDL_Surface* g = SDL_LoadBMP("letters/g.bmp");
SDL_Surface* h = SDL_LoadBMP("letters/h.bmp");
SDL_Surface* j = SDL_LoadBMP("letters/j.bmp");
SDL_Surface* k = SDL_LoadBMP("letters/k.bmp");
SDL_Surface* l = SDL_LoadBMP("letters/l.bmp");
SDL_Surface* z = SDL_LoadBMP("letters/z.bmp");
SDL_Surface* xi = SDL_LoadBMP("letters/x.bmp");
SDL_Surface* c = SDL_LoadBMP("letters/c.bmp");
SDL_Surface* v = SDL_LoadBMP("letters/v.bmp");
SDL_Surface* b = SDL_LoadBMP("letters/b.bmp");
SDL_Surface* n = SDL_LoadBMP("letters/n.bmp");
SDL_Surface* m = SDL_LoadBMP("letters/m.bmp");

SDL_Surface* alf[901];
